### ISSUE TITLE
upload source code to f-droid so newest version can be placed in repo

### ISSUE THREAD

**Issue by landry314** [GiorgioRegni/Binaural-Beats#12]
the version in f-droid is way behind:
https://f-droid.org/repository/browse/?fdid=com.ihunda.android.binauralbeat

the new source code needs to be updated.

**Comment by GiorgioRegni** [comment]
@landry314 I am not familiar with f-droid, why is it a good idea to upload there?

**Comment by landry314** [comment]
well, it is already uploaded there, it is just a very old version.

f-droid is a repository of completely free open source android apps. i go there because i love to support open source... and i dont trust google and i dont have google apps installed.

**Comment by landry314** [comment]
https://gitlab.com/fdroid/fdroiddata/blob/master/README.md

https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by Mr-Kumar-Abhishek** [comment]
I have got your app from f-droid yesterday . i loved it. Very useful. If it is an old one their please update it. I was trying to find more about this but apparently , forums links are broken on the app.

**Comment by landry314** [comment]
yeah, it is amazing, huh? the version on the play store is much newer if you can get it somehow. i wish i could send you the apk.

there are websites where you can download from the play store without a google account. like this one:

https://apps.evozi.com/apk-downloader/

i cant guarantee it is safe but it has been around for years and i have never heard of malware going through it. of course, if you can use a friend's phone who has a play store then rip the apk (i recommend es file manager to do that) then that is the best.

**Comment by SecUpwN** [comment]
>I am not familiar with f-droid, why is it a good idea to upload there?

@GiorgioRegni, F-Droid automatically builds and publishes your app with a different signature, you basically do not have to do anything and just change the version code and F-Droid launches a build.

As you've already seen, I have linked your app to your F-Droid app page in the refreshed `README`. 
Every app also has a separate repository page, for this app it is [com.ihunda.android.binauralbeat](https://f-droid.org/wiki/page/com.ihunda.android.binauralbeat).

And there we are at the core of why F-Droid does not build the latest release. Current version `4.7`:

>We can't build this version: The build for this version was manually disabled. Reason: play-services

F-Droid analyzes your source code and detected GooglePlay services. Since F-Droid only promotes pure FOSS software, the key solution would be to *fully replace* the unfree GooglePlay services.

Also, if you have a look at the current *Maintainer Notes*:

>RepoManifest used for indication of changes only. Commits that change AndroidManifest.xml are not made at release time, if at all, and source code is rarely up to date or correct.

It seems you're not using an `AndroidManifest.xml` where changes are indicated. I am not sure if you need to change this as well after removing or replacing the GooglePlay services. Does he have to, @krt?

**Comment by asl97** [comment]
@SecUpwN It doesn't even use the play services does it?

The only three places where it even mention them are:
[AndroidManifest.xml](https://github.com/GiorgioRegni/Binaural-Beats/blob/d6c4383b42201f0d36238a7ab9c55a8c0bf1d59a/AndroidManifest.xml#L37), [project.properties](https://github.com/GiorgioRegni/Binaural-Beats/blob/d6c4383b42201f0d36238a7ab9c55a8c0bf1d59a/project.properties#L12) and [IInAppBillingService.aidl](https://github.com/GiorgioRegni/Binaural-Beats/blob/26e568be8cd5054df24b60adc2fed67ec8b384b6/src/com/android/vending/billing/IInAppBillingService.aidl)

Which were added by the [facebook integration](https://github.com/GiorgioRegni/Binaural-Beats/commit/26e568be8cd5054df24b60adc2fed67ec8b384b6)
