### ISSUE TITLE
Phone calls crash app

### ISSUE THREAD

**Issue by TheCoose** [GiorgioRegni/Binaural-Beats#9]
Binaural Beats crashes when making or receiving phone calls. App is not running (must be running in background). What I mean is that I'm not running the app and it's hasn't been opened yet. What ever services are running is what crashes. Not sure why there would even be services running prior to app launch. Using a Note 2 running 4.1.1

**Comment by SecUpwN** [comment]
@GiorgioRegni, as you may have noticed with my pull request, I really love your app. But you please do all users the favor and actually review all open Issues and make promises like https://github.com/GiorgioRegni/Binaural-Beats/issues/9#issuecomment-22923519 come true? ;-)

**Comment by jjgh** [comment]
Yeah, I am with @SecUpwN on that..

Also @GiorgioRegni , there have been people asking you if you have time to mantain this, but issues have been left unattended for 2 years... Why not let someone else mantain this project if you can't/don't have time?
This  app has very good  foundations compared to other ones so that's why people would like to help! Cheers man!

**Comment by GiorgioRegni** [comment]
I am open to having extra maintainers, so far nobody stepped up. If you're interested @jjgh, we can talk about that!

**Comment by GiorgioRegni** [comment]
I think this particular issue is fixed and I should close it unless you still have the problem with phone calls.

**Comment by jjgh** [comment]
@GiorgioRegni I apologize but after quickly skimming through the issues I was under the impression that @kevencarneiro actually wanted to step up as a new maintainer but yeah I see that you guys are still discussing that. 
With regards to me I'm sorry but I'm not the right person for this kind of task, yet :)
